owner: imm0r
repo: MTGTC-Archive-Status
sites:
  - name: App
    url: https://imm0r.github.io/MTGTC-Archive/
  - name: Font1
    url: https://imm0r.github.io/MTGTC-Archive/assets/keyrune/keyrune.woff2
  - name: Font2
    url: https://imm0r.github.io/MTGTC-Archive/assets/mana/mana.woff2
  - name: API
    url: https://api.supabase.co/health
